### ISSUE TITLE
Boxplots for Translation and Orientation Error, Calculation of Travelled Distance, 2D Plot

### ISSUE THREAD

**Issue by surberj** [ethz-asl/trajectory_toolkit#2]
I implemented calculations and plotting functions of the signals in the title on the old python/c++ Repository c_easytrajectorymanager. 
If you are not already working on it, I can port it to this repo untill the end of the week and open a pr.

**Comment by bloesch** [comment]
I am on holiday until mid december. It would be very nice if you could port it to this repo.ideally you would put the error calculation into the TimedData class. I ll have a look at the PR as soon as I am back.
